# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# Useful links:
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
      push:
            branches: ['main']
      pull_request:
            branches: ['main']

jobs:
      build:
            # Image to run on
            runs-on: ubuntu-latest

            steps:
                  - uses: actions/checkout@v4
                  - name: Use Node.js
                    uses: actions/setup-node@v3
                    with:
                          # https://nodejs.org/en (select the version of LTS (long term support))
                          node-version: '20.10.0'
                  - run: npm ci
                  - run: npm run build --if-present
                  - run: npm run test
